services:
  - type: web
    name: food-analyzer
    env: python
    startCommand: "python app.py"
    envVars:
      - key: GEMINI_API_KEY
        sync: false
      - key: MONGODB_URI
        sync: false
    plan: free
