services:
  - type: web
    name: food-analyzer
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app --workers 1 --threads 4 --timeout 120 --bind 0.0.0.0:$PORT --preload"
    envVars:
      - key: GEMINI_API_KEY
      - key: MONGO_URI
      - key: MONGO_DB
        value: food-app-swift
      - key: JWT_SECRET_KEY
      - key: ENVIRONMENT
        value: production
    plan: free
    healthCheckPath: /health