services:
  - type: web
    name: food-analyzer
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app --workers 2 --threads 4 --timeout 120"
    envVars:
      - key: GEMINI_API_KEY
        sync: false
      - key: MONGO_URI
        sync: false
      - key: MONGO_DB
        value: food-app-swift
    plan: free
    healthCheckPath: /health